// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	models "github.com/natalya-revtova/system-monitoring/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Grabber is an autogenerated mock type for the Grabber type
type Grabber struct {
	mock.Mock
}

// Grab provides a mock function with given fields: results
func (_m *Grabber) Grab(results chan models.Metrics) {
	_m.Called(results)
}

// NewGrabber creates a new instance of Grabber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGrabber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Grabber {
	mock := &Grabber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
