// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.1
// source: monitoring.proto

package monitoringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SystemMonitoring_CollectMetrics_FullMethodName = "/monitoring.SystemMonitoring/CollectMetrics"
)

// SystemMonitoringClient is the client API for SystemMonitoring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemMonitoringClient interface {
	CollectMetrics(ctx context.Context, in *CollectParams, opts ...grpc.CallOption) (SystemMonitoring_CollectMetricsClient, error)
}

type systemMonitoringClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemMonitoringClient(cc grpc.ClientConnInterface) SystemMonitoringClient {
	return &systemMonitoringClient{cc}
}

func (c *systemMonitoringClient) CollectMetrics(ctx context.Context, in *CollectParams, opts ...grpc.CallOption) (SystemMonitoring_CollectMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SystemMonitoring_ServiceDesc.Streams[0], SystemMonitoring_CollectMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &systemMonitoringCollectMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SystemMonitoring_CollectMetricsClient interface {
	Recv() (*Result, error)
	grpc.ClientStream
}

type systemMonitoringCollectMetricsClient struct {
	grpc.ClientStream
}

func (x *systemMonitoringCollectMetricsClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SystemMonitoringServer is the server API for SystemMonitoring service.
// All implementations must embed UnimplementedSystemMonitoringServer
// for forward compatibility
type SystemMonitoringServer interface {
	CollectMetrics(*CollectParams, SystemMonitoring_CollectMetricsServer) error
	mustEmbedUnimplementedSystemMonitoringServer()
}

// UnimplementedSystemMonitoringServer must be embedded to have forward compatible implementations.
type UnimplementedSystemMonitoringServer struct {
}

func (UnimplementedSystemMonitoringServer) CollectMetrics(*CollectParams, SystemMonitoring_CollectMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method CollectMetrics not implemented")
}
func (UnimplementedSystemMonitoringServer) mustEmbedUnimplementedSystemMonitoringServer() {}

// UnsafeSystemMonitoringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemMonitoringServer will
// result in compilation errors.
type UnsafeSystemMonitoringServer interface {
	mustEmbedUnimplementedSystemMonitoringServer()
}

func RegisterSystemMonitoringServer(s grpc.ServiceRegistrar, srv SystemMonitoringServer) {
	s.RegisterService(&SystemMonitoring_ServiceDesc, srv)
}

func _SystemMonitoring_CollectMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemMonitoringServer).CollectMetrics(m, &systemMonitoringCollectMetricsServer{stream})
}

type SystemMonitoring_CollectMetricsServer interface {
	Send(*Result) error
	grpc.ServerStream
}

type systemMonitoringCollectMetricsServer struct {
	grpc.ServerStream
}

func (x *systemMonitoringCollectMetricsServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

// SystemMonitoring_ServiceDesc is the grpc.ServiceDesc for SystemMonitoring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemMonitoring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitoring.SystemMonitoring",
	HandlerType: (*SystemMonitoringServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectMetrics",
			Handler:       _SystemMonitoring_CollectMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "monitoring.proto",
}
